### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by darshancc23** [darshancc23/photopia#13]
Need to improve the documentation. You can add screenshots, explain about the project, etc.

To set up the project in your local machine follow the steps in the [README.md](https://github.com/darshancc23/photopia/blob/master/README.md) file

**Comment by nihitb06** [comment]
I'll update the ReadMe and add comments to the code for the tricky parts

**Comment by darshancc23** [comment]
@nihitb06 Thank you

**Comment by nihitb06** [comment]
I just opened a Pull Request. Kindly see if it is sufficient.

**Comment by darshancc23** [comment]
@nihitb06 Awesome, Thank you so much!

**Comment by nihitb06** [comment]
Happy to help
